name: Build

on:
  push:
  pull_request:

jobs:
  build:
    name: Build project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Test secrets
        run: |
          echo "Behold: $TEST_SECRET"
        env:
          TEST_SECRET: ${{ secrets.TEST_SECRET }}
