name: Build

on:
  push:
  pull_request:

jobs:
  build:
    name: Build project
    runs-on: ubuntu-latest
    strategy:
      matrix:
        greeting: ['CITY', 'WORLD', 'UNIVERSE']
    steps:
      - name: Checkout project
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Test secrets
        run: |
          echo "Behold $GREETING: $TEST_SECRET"
        env:
          TEST_SECRET: ${{ secrets.TEST_SECRET }}
          GREETING: ${{ matrix.greeting }}
      - name: Upload README
        if: github.event_name == 'pull_request' && matrix.greeting == 'UNIVERSE'
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.greeting }}
          path: README.md
