name: Sonar Call

on:
  workflow_call:

jobs:
  Sonar:
    name: Sonar
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.event == 'pull_request'
    steps:
      - name: Test secrets
        run: |
          echo "Sonar: $TEST_SECRET"
        env:
          TEST_SECRET: ${{ secrets.TEST_SECRET }}
