name: Sonar Run

on:
  workflow_run:
    workflows: [Build]
    types: [completed]

jobs:
  Sonar:
    name: Sonar
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success'
    steps:
      - name: Test secrets
        run: |
          echo "Sonar: $TEST_SECRET"
        env:
          TEST_SECRET: ${{ secrets.TEST_SECRET }}
